name: Lint and Coverage

on:
  workflow_dispatch:
  pull_request:
    types: ["opened", "synchronize", "ready_for_review"]

jobs:
  lint:
    needs: get-changed-files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Ruff
        run: python -m pip install ruff
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: ruff check --fix --output-format=github .
